# Generated by Django 3.0.3 on 2020-06-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200601_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_name',
            field=models.CharField(default='XYZ', max_length=100),
        ),
    ]
