# Generated by Django 3.0.3 on 2020-06-07 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200605_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_on',
            field=models.DateField(default=datetime.datetime(2020, 6, 7, 19, 12, 41, 614140)),
        ),
    ]
